### ISSUE TITLE
Registered user cannot log in

### ISSUE THREAD

**Issue by mshuflin** [evanreichard/AnthoLume#1]
When I create a user on the /register page, it redirects to the /login page. Then logging in with the newly created credentials, there is no error, but hitting submit does not go anywhere (simply reloads the login page).

If I try to re-register, I receive "Registration Disabled or User Already Exists" and if I enter the incorrect credentials on the login screen I receive "Invalid Credentials."

Nothing in the log other than Gin registering me loading the pages (login and register)

**Comment by evanreichard** [comment]
My hunch would be you're accessing it over HTTP (not HTTPS), and don't have the environment variable set `COOKIE_SECURE=false`.

Set the environment variable `COOKIE_SECURE=false` and try again. If that doesn't work, let me know what version you're running (dev (master), or tagged 0.0.1)

___


**Edit:** I updated the "Quick Start" instructions in the README to include the environment variable, as well as a note emphasizing the setting.

**Comment by mshuflin** [comment]
That did it, thanks for the quick help.
