### ISSUE TITLE
Text stretched on Daily Read Totals graph on large screens

### ISSUE THREAD

**Issue by mshuflin** [evanreichard/AnthoLume#2]
A minor UI issue I noticed, the text shown when I hover over the daily read totals is stretched. This improves if I reduce the width of the browser window.
![Screenshot 2024-01-31 at 10 58 20 AM](https://github.com/evanreichard/AnthoLume/assets/53985056/bc8b11b7-9eac-443c-be34-c34aece4bef3)

**Comment by Evan-Prophet** [comment]
Hey, I appreciate the bug report. This has been bothering me for awhile too and your report inspired me to give it some attention. Managed to fix it (https://github.com/evanreichard/AnthoLume/commit/b319f7d39a715a07a3496c8435bad13f11207456) and added some better styling.

___

<img width="1292" alt="Screenshot 2024-02-01 at 19 01 22" src="https://github.com/evanreichard/AnthoLume/assets/155461086/48657192-efd4-4e10-bfee-de1aee19c3c2">
<img width="653" alt="Screenshot 2024-02-01 at 19 01 29" src="https://github.com/evanreichard/AnthoLume/assets/155461086/700e0b4d-a5d2-461c-8dec-44c43d75f907">

**Comment by evanreichard** [comment]
Hey, I appreciate the bug report. This has been bothering me for awhile too and your report inspired me to give it some attention. Managed to fix it (https://github.com/evanreichard/AnthoLume/commit/4a5464853be92d0bf4f0dfa9756093b4587f9d2d) and added some better styling.

___

<img width="1292" alt="Screenshot 2024-02-01 at 19 01 22" src="https://github.com/evanreichard/AnthoLume/assets/155461086/48657192-efd4-4e10-bfee-de1aee19c3c2">
<img width="653" alt="Screenshot 2024-02-01 at 19 01 29" src="https://github.com/evanreichard/AnthoLume/assets/155461086/700e0b4d-a5d2-461c-8dec-44c43d75f907">

**Comment by mshuflin** [comment]
I am still finding this to be an issue on my larger screen. Everything looks fine if I am only using my laptop screen, but on my larger monitor, the stats are still stretched. I tried removing and re-pulling the docker image to be sure I was using the latest version

**Comment by evanreichard** [comment]
Hey @mshuflin - what tag are you using? There hasn't been an official release since 0.0.1, but the dev image tag should have the above changes.

If you're upgrading from 0.0.1 to dev - be sure to backup.

Sorry about the lack of a release! I'm still slowly working on this, work has just taken priority over the last few months.

**Comment by mshuflin** [comment]
I was just using the `latest` tag, I will try the dev version. Thanks for the support and for sharing such a great project!
