### ISSUE TITLE
Point to existing library

### ISSUE THREAD

**Issue by mission-ajennings** [evanreichard/AnthoLume#3]
Hello, sorry for opening an issue as this is more of a question. This is a super sleek project, I've been looking for something like this with reading stats. My question is, is there a way to point it at an existing directory of epubs or anything like that or does it only support uploading one at a time? Thanks!

Edit to say I'm running the container and I mean mount the ebook directory to data or another dir

**Comment by evanreichard** [comment]
Hey @mission-ajennings 

Don't worry about asking questions here, I don't mind at all.

There is the ability to import when using the `dev` docker image tag (`docker pull gitea.va.reichard.io/evan/antholume:dev`). It will ask you whether you want to copy ("Copy") the found files to the AnthoLume data directory, or reference them directly in the DB ("Direct").

### Note
Before doing any of that I recommend backing up AnthoLume configuration before updating to `dev` (if you're on `latest` or `0.0.1`), as well as making sure you have a backup of your existing data that you intend on importing.

It shouldn't ever modify or delete the files, and I've tested on my own data without incident, but just to be extra safe.
___
<img width="500" alt="Screenshot 2024-09-25 at 20 21 46" src="https://github.com/user-attachments/assets/e3f410a7-c432-473b-b092-537c61c9ccca">

**Comment by evanreichard** [comment]
I am planning a new release sometime in the next couple months that will have all of these features, I've just been pretty busy with other obligations so I haven't given this project as much attention as I'd like.

**Comment by mission-ajennings** [comment]
awesome @evanreichard thanks for the response. I can't wait to see where you take this project
